org: karashiiro
app: dalamud-plugin-dl-count-gh-badge
service: dalamud-plugin-dl-count-gh-badge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    url: true
    events:
      - httpApi: '*'
